---
abstract: 'An incremental logparser to be used with Net-SNMP'
author:
  - 'Nito Martinez <nito@qindel.es>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SNMP-LogParser
provides:
  SNMP::LogParser:
    file: lib/SNMP/LogParser.pm
    version: 1.10052
  SNMP::LogParserDriver:
    file: lib/SNMP/LogParserDriver.pm
  SNMP::LogParserDriver::ExampleDriver:
    file: lib/SNMP/LogParserDriver/ExampleDriver.pm
  SNMP::LogparserDriver::ProxyLog:
    file: lib/SNMP/LogParserDriver/ProxyLog.pm
requires:
  Config::Properties::Simple: 0.14
  File::Path: 1.05
  File::Spec: 0
  File::Temp: 0
  File::stat: 0
  Log::Dispatch::FileRotate: 0
  Log::Log4perl: 0
  POSIX: 0
  Pod::Usage: 0
  Proc::ProcessTable: 0
  Statistics::Descriptive: 0
  Storable: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
resources:
  license: http://dev.perl.org/licenses/
version: 1.10052
