---
name: SNMP-LogParser
version: 1.0767
author:
  - 'Nito Martinez <nito@qindel.es>'
abstract: An incremental logparser to be used with Net-SNMP
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Config::Properties::Simple: 0.14
  File::Path: 1.05
  File::Spec: 0
  File::Temp: 0
  File::stat: 0
  Log::Dispatch::FileRotate: 0
  Log::Log4perl: 0
  POSIX: 0
  Pod::Usage: 0
  Proc::ProcessTable: 0
  Statistics::Descriptive: 0
  Storable: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  SNMP::LogParser:
    file: lib/SNMP/LogParser.pm
    version: 1.0767
  SNMP::LogParserDriver:
    file: lib/SNMP/LogParserDriver.pm
  SNMP::LogParserDriver::ExampleDriver:
    file: lib/SNMP/LogParserDriver/ExampleDriver.pm
  SNMP::LogparserDriver::ProxyLog:
    file: lib/SNMP/LogParserDriver/ProxyLog.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
